// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdA5PzJinZXURxtWEN3FqLkfM-jcfPebI',
    appId: '1:669597560426:android:07b3ea34e10a5b9da0a413',
    messagingSenderId: '669597560426',
    projectId: 'fluttergram-7510c',
    storageBucket: 'fluttergram-7510c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD4RHy5K0Q9AwUkIcT0ojH6AH9VKl-Ejw',
    appId: '1:669597560426:ios:36029e75aaba4c74a0a413',
    messagingSenderId: '669597560426',
    projectId: 'fluttergram-7510c',
    storageBucket: 'fluttergram-7510c.appspot.com',
    iosClientId: '669597560426-lhpq9h4m3ts3c1bs984luhovem9eh8a1.apps.googleusercontent.com',
    iosBundleId: 'com.a810.instagram',
  );
}
